//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlazorApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DataDictionary {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DataDictionary() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BlazorApp.Resources.DataDictionary", typeof(DataDictionary).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Website is MULTI LANGUAGE, you can change to Farsi from menu.
        /// </summary>
        internal static string AlertLang {
            get {
                return ResourceManager.GetString("AlertLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soundex is a phonetic algorithm for indexing names by sound, as pronounced in English. 
        ///        The goal is for homophones to be encoded to the same representation so that they can be 
        ///        matched despite minor differences in spelling. The algorithm mainly encodes consonants;
        ///        a vowel will not be encoded unless it is the first letter. Soundex is the most widely known 
        ///        of all phonetic algorithms (in part because it is a standard feature of popular database software 
        ///        such as IB [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CardBody {
            get {
                return ResourceManager.GetString("CardBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More here!.
        /// </summary>
        internal static string CardBtn {
            get {
                return ResourceManager.GetString("CardBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is soundex?.
        /// </summary>
        internal static string CardTitle {
            get {
                return ResourceManager.GetString("CardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SoundexDemo.
        /// </summary>
        internal static string NavBarlogo {
            get {
                return ResourceManager.GetString("NavBarlogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Algorithm.
        /// </summary>
        internal static string NavBarMenuAlgo {
            get {
                return ResourceManager.GetString("NavBarMenuAlgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Github.
        /// </summary>
        internal static string NavBarMenuGithub {
            get {
                return ResourceManager.GetString("NavBarMenuGithub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string NavBarMenuHome {
            get {
                return ResourceManager.GetString("NavBarMenuHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soundex Search.
        /// </summary>
        internal static string TestCardButton {
            get {
                return ResourceManager.GetString("TestCardButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string TestCardLabel {
            get {
                return ResourceManager.GetString("TestCardLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TRY HERE ✔️.
        /// </summary>
        internal static string TestCardTitle {
            get {
                return ResourceManager.GetString("TestCardTitle", resourceCulture);
            }
        }
    }
}
